// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLkSPnXprPnl84uY0sEXwyuL3QPTv-mI',
    appId: '1:562146848418:web:b2af47d7416141cffbf1fb',
    messagingSenderId: '562146848418',
    projectId: 'regradocorte-42198',
    authDomain: 'regradocorte-42198.firebaseapp.com',
    databaseURL: 'https://regradocorte-42198-default-rtdb.firebaseio.com',
    storageBucket: 'regradocorte-42198.appspot.com',
    measurementId: 'G-2TSYMFJWDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl6C-fzUb5H4qZKLPRIEWRI5wWh_pLock',
    appId: '1:562146848418:android:bbb3bf38e7a79cc6fbf1fb',
    messagingSenderId: '562146848418',
    projectId: 'regradocorte-42198',
    databaseURL: 'https://regradocorte-42198-default-rtdb.firebaseio.com',
    storageBucket: 'regradocorte-42198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlt-CfKq0B_zoiTmgbElKx66QTIMNOvTY',
    appId: '1:562146848418:ios:3b5d834c072fde82fbf1fb',
    messagingSenderId: '562146848418',
    projectId: 'regradocorte-42198',
    databaseURL: 'https://regradocorte-42198-default-rtdb.firebaseio.com',
    storageBucket: 'regradocorte-42198.appspot.com',
    iosBundleId: 'com.example.regradocorteAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlt-CfKq0B_zoiTmgbElKx66QTIMNOvTY',
    appId: '1:562146848418:ios:ddebc336aeb27175fbf1fb',
    messagingSenderId: '562146848418',
    projectId: 'regradocorte-42198',
    databaseURL: 'https://regradocorte-42198-default-rtdb.firebaseio.com',
    storageBucket: 'regradocorte-42198.appspot.com',
    iosBundleId: 'com.example.regradocorteAppNew.RunnerTests',
  );
}
